export enum UserRole {
  SITE_INCHARGE = 'SITE_INCHARGE',
  STORE_INCHARGE = 'STORE_INCHARGE',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  EXECUTIVE = 'EXECUTIVE',
  COORDINATOR = 'COORDINATOR',
  CHAIRMAN = 'CHAIRMAN',
}

export enum MaterialRequestStatus {
  PENDING_STORE = 'PENDING_STORE',
  ALLOCATED = 'ALLOCATED',
  FORWARDED_TO_PM = 'FORWARDED_TO_PM',
  BRANCH_TRANSFER_REQUESTED = 'BRANCH_TRANSFER_REQUESTED',
  PENDING_HO = 'PENDING_HO',
  PENDING_EXECUTIVE_DECISION = 'PENDING_EXECUTIVE_DECISION',
  EXECUTIVE_DECISION_PO = 'EXECUTIVE_DECISION_PO',
  EXECUTIVE_DECISION_BRANCH_TRANSFER = 'EXECUTIVE_DECISION_BRANCH_TRANSFER',
  PM_APPROVED = 'PM_APPROVED',
  PURCHASE_REQUESTED = 'PURCHASE_REQUESTED',
  RFQ_OPEN = 'RFQ_OPEN',
  QUOTED = 'QUOTED',
  VENDOR_SELECTED = 'VENDOR_SELECTED',
  PO_CREATED = 'PO_CREATED',
  COORDINATOR_VERIFIED = 'COORDINATOR_VERIFIED',
  CHAIRMAN_APPROVED = 'CHAIRMAN_APPROVED',
  MATERIAL_RECEIVED = 'MATERIAL_RECEIVED',
  ISSUED = 'ISSUED',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  CLOSED = 'CLOSED',
}

export enum StockMovementType {
  ALLOCATION = 'ALLOCATION',
  INCOMING = 'INCOMING',
  ADJUSTMENT = 'ADJUSTMENT',
}

export enum PurchaseOrderStatus {
  DRAFT = 'DRAFT',
  PM_PENDING = 'PM_PENDING',
  COORDINATOR_PENDING = 'COORDINATOR_PENDING',
  COORDINATOR_VERIFIED = 'COORDINATOR_VERIFIED',
  CHAIRMAN_PENDING = 'CHAIRMAN_PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum WorkOrderStatus {
  DRAFT = 'DRAFT',
  PM_PENDING = 'PM_PENDING',
  EXECUTIVE_PENDING = 'EXECUTIVE_PENDING',
  COORDINATOR_PENDING = 'COORDINATOR_PENDING',
  CHAIRMAN_PENDING = 'CHAIRMAN_PENDING',
  PENDING_ACCEPTANCE = 'PENDING_ACCEPTANCE',
  ACCEPTED = 'ACCEPTED',
  IN_PROGRESS = 'IN_PROGRESS',
  CLOSED = 'CLOSED',
  REJECTED = 'REJECTED',
}

export enum BranchTransferStatus {
  REQUESTED = 'REQUESTED',
  EXECUTIVE_APPROVED = 'EXECUTIVE_APPROVED',
  DISPATCHED = 'DISPATCHED',
  PARTIALLY_RECEIVED = 'PARTIALLY_RECEIVED',
  PM_APPROVED = 'PM_APPROVED',
  COORDINATOR_DECIDED = 'COORDINATOR_DECIDED',
  TRANSFERRED = 'TRANSFERRED',
  REJECTED = 'REJECTED',
  RAISE_PO_INSTEAD = 'RAISE_PO_INSTEAD',
}

export enum WorkOrderMilestoneStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
}

export enum ProjectStatus {
  ACTIVE = 'ACTIVE',
  ON_HOLD = 'ON_HOLD',
  COMPLETED = 'COMPLETED',
}

export type Capability =
  | 'VIEW_OWN_SCOPE'
  | 'VIEW_ALL_PROJECTS'
  | 'CREATE_MATERIAL_REQUEST'
  | 'EDIT_MATERIAL_REQUEST'
  | 'ALLOCATE_MATERIAL_REQUEST'
  | 'FORWARD_MATERIAL_REQUEST'
  | 'APPROVE_MATERIAL_REQUEST'
  | 'CREATE_PURCHASE_REQUEST'
  | 'CREATE_RFQ'
  | 'SELECT_VENDOR'
  | 'CREATE_PO'
  | 'VERIFY_RECORDS'
  | 'FINAL_APPROVAL'
  | 'EDIT_ALLOCATION_QTY'
  | 'EDIT_PROJECT_SCOPE'
  | 'EDIT_PROCUREMENT'
  | 'VIEW_FINANCE'
  | 'VIEW_AUDIT_LOGS'
  | 'MANAGE_USERS'
  | 'CREATE_WORK_ORDER'
  | 'ISSUE_WO_MATERIAL'
  | 'TRACK_WO_PROGRESS'
  | 'CERTIFY_WO_WORK'
  | 'CREATE_INVENTORY_ITEM'
  | 'DELETE_INVENTORY_ITEM'
  | 'DELETE_RECORDS'
  | 'EDIT_COORDINATOR_RECORDS'
  | 'RECEIVE_MATERIAL'
  | 'VERIFY_DELIVERY'
  | 'ISSUE_MATERIAL'
  | 'CREATE_BRANCH_TRANSFER'
  | 'MANAGE_PROJECTS'
  | 'REPORT_INCIDENT'
  | 'MANAGE_VENDORS'
  | 'CREATE_VENDOR'
  | 'VIEW_INCIDENTS'
  | 'RESOLVE_INCIDENT'
  | 'VIEW_USER_ANALYTICS';

export const PERMISSION_MATRIX: Record<UserRole, Capability[]> = {
  [UserRole.SITE_INCHARGE]: [
    'VIEW_OWN_SCOPE',
    'CREATE_MATERIAL_REQUEST',
    'EDIT_MATERIAL_REQUEST',
    'REPORT_INCIDENT',
  ],
  [UserRole.STORE_INCHARGE]: [
    'VIEW_OWN_SCOPE',
    'CREATE_MATERIAL_REQUEST',
    'EDIT_MATERIAL_REQUEST',
    'VIEW_FINANCE',
    'ALLOCATE_MATERIAL_REQUEST',
    'FORWARD_MATERIAL_REQUEST',
    'EDIT_ALLOCATION_QTY',
    'CREATE_INVENTORY_ITEM',
    'VERIFY_DELIVERY',
    'RECEIVE_MATERIAL',
    'ISSUE_MATERIAL',
    'REPORT_INCIDENT',
  ],
  [UserRole.PROJECT_MANAGER]: [
    'VIEW_OWN_SCOPE',
    'EDIT_MATERIAL_REQUEST',
    'ALLOCATE_MATERIAL_REQUEST',
    'FORWARD_MATERIAL_REQUEST',
    'APPROVE_MATERIAL_REQUEST',
    'CREATE_PURCHASE_REQUEST',
    'EDIT_PROJECT_SCOPE',
    'VIEW_FINANCE',
    'TRACK_WO_PROGRESS',
    'CREATE_INVENTORY_ITEM',
    'REPORT_INCIDENT',
    'VIEW_INCIDENTS',
    'CREATE_BRANCH_TRANSFER',
  ],
  [UserRole.EXECUTIVE]: [
    'VIEW_ALL_PROJECTS',
    'EDIT_MATERIAL_REQUEST',
    'APPROVE_MATERIAL_REQUEST',
    'CREATE_PURCHASE_REQUEST',
    'CREATE_RFQ',
    'SELECT_VENDOR',
    'CREATE_PO',
    'CREATE_WORK_ORDER',
    'EDIT_PROCUREMENT',
    'CREATE_VENDOR',
    'VIEW_FINANCE',
  ],
  [UserRole.COORDINATOR]: [
    'VIEW_ALL_PROJECTS',
    'EDIT_MATERIAL_REQUEST',
    'VERIFY_RECORDS',
    'EDIT_COORDINATOR_RECORDS',
    'CREATE_WORK_ORDER',
    'VIEW_FINANCE',
    'VIEW_AUDIT_LOGS',
    'CREATE_INVENTORY_ITEM',
    'DELETE_INVENTORY_ITEM',
    'DELETE_RECORDS',
    'MANAGE_PROJECTS',
    'MANAGE_VENDORS',
    'RECEIVE_MATERIAL',
    'VIEW_INCIDENTS',
    'RESOLVE_INCIDENT',
    'CREATE_BRANCH_TRANSFER',
    'APPROVE_MATERIAL_REQUEST',
  ],
  [UserRole.CHAIRMAN]: [
    'VIEW_ALL_PROJECTS',
    'FINAL_APPROVAL',
    'VIEW_FINANCE',
    'VIEW_USER_ANALYTICS',
  ],
};

export const ROLE_COLORS: Record<UserRole, { primary: string; accent: string }> = {
  [UserRole.SITE_INCHARGE]: { primary: '#1A4FA0', accent: '#E8F0FA' },
  [UserRole.STORE_INCHARGE]: { primary: '#1A4FA0', accent: '#E8F0FA' },
  [UserRole.PROJECT_MANAGER]: { primary: '#7C3AED', accent: '#F5F3FF' },
  [UserRole.EXECUTIVE]: { primary: '#1A4FA0', accent: '#E8F0FA' },
  [UserRole.COORDINATOR]: { primary: '#0D9488', accent: '#F0FDFA' },
  [UserRole.CHAIRMAN]: { primary: '#1A4FA0', accent: '#E8F0FA' },
};

export const ROLE_LABELS: Record<UserRole, string> = {
  [UserRole.SITE_INCHARGE]: 'New indent',
  [UserRole.STORE_INCHARGE]: 'Store Incharge',
  [UserRole.PROJECT_MANAGER]: 'Project Manager',
  [UserRole.EXECUTIVE]: 'Executive',
  [UserRole.COORDINATOR]: 'Coordinator',
  [UserRole.CHAIRMAN]: 'Chairman / MD',
};

export * from './formatters';
export * from './dtos';
export * from './locales';
export * from './materialConstants';
export * from './gstMath';
export * from './indentRequestTypes';
export * from './indentEditPolicy';
